version: '3.8'

services:
  nginx:
    image: nginx:stable-alpine
    container_name: vue3-study-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./dist:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./ssl:/etc/nginx/ssl
    restart: unless-stopped
    networks:
      - vue3-study-network

networks:
  vue3-study-network:
    driver: bridge